[13:26:51:715]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Incorrect integer value: '订单确认中' for column 'order_statu' at row 1
[13:27:15:575]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Incorrect integer value: '订单确认中' for column 'order_statu' at row 1
[13:27:42:609]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Incorrect integer value: '订单确认中' for column 'order_statu' at row 1
[13:27:53:863]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Incorrect integer value: '订单确认中' for column 'order_statu' at row 1
[13:28:11:964]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Incorrect integer value: '订单确认中' for column 'order_statu' at row 1
[13:29:41:899]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Table 'meetfood.t_apply_order' doesn't exist
[20:08:43:736]|[ERROR]|org.hibernate.engine.jdbc.spi.SqlExceptionHelper|logExceptions|Table 'meetfood.t_user_dynamic' doesn't exist
